export { color, composeColors } from './core/color.js'
export { getConfig } from './core/config.js'
export { env, Env } from './core/env.js'
export { Flashcore } from './core/flashcore.js'
export { createCommandConfig } from './core/handlers.js'
export { createPluginState, inferNamespace } from './core/hooks.js'
export { logger, Logger } from './core/logger.js'
export { Manifest } from './core/manifest-api.js'
export { Mode } from './core/mode.js'
export { getPluginOptions } from './core/portal.js'
export { portal, Robo } from './core/robo.js'
export { getState, setState, State } from './core/state.js'
export type { LogDrain } from './core/logger.js'
export type * from './types/index.js'
