/**
 * Flashcore v1 (spec rev 4.3) ID Generation
 *
 * Provides collision-resistant ID generation for model records.
 */

/**
 * Counter for ensuring uniqueness within the same millisecond.
 */
let counter = 0

/**
 * Last timestamp used for ID generation.
 */
let lastTimestamp = 0

/**
 * Generate a collision-resistant ID.
 *
 * Format: {timestamp}-{counter}-{random}
 * - timestamp: base36 encoded milliseconds since epoch
 * - counter: monotonic counter for same-millisecond uniqueness
 * - random: random component for cross-process uniqueness
 *
 * Properties:
 * - Roughly sortable by creation time
 * - Safe characters (alphanumeric + hyphen)
 * - Collision-resistant in single process
 * - Reasonably unique across processes
 *
 * @returns Generated ID string
 */
export function generateId(): string {
	const now = Date.now()

	// Reset counter if we've moved to a new millisecond
	if (now !== lastTimestamp) {
		counter = 0
		lastTimestamp = now
	}

	// Increment counter for same-millisecond uniqueness
	counter++

	// Generate random component
	const random = Math.random().toString(36).substring(2, 8)

	// Encode timestamp and counter as base36
	const timestamp = now.toString(36)
	const count = counter.toString(36).padStart(4, '0')

	return `${timestamp}-${count}-${random}`
}

/**
 * Generate a random ID (no timestamp component).
 *
 * Useful when time-based ordering is not needed.
 *
 * @returns Random ID string
 */
export function generateRandomId(): string {
	const parts: string[] = []

	// Generate 4 random segments
	for (let i = 0; i < 4; i++) {
		parts.push(Math.random().toString(36).substring(2, 8))
	}

	return parts.join('-')
}

/**
 * Validate an ID string.
 *
 * @param id - ID to validate
 * @returns True if valid
 */
export function isValidId(id: string): boolean {
	if (typeof id !== 'string') {
		return false
	}

	if (id.length === 0 || id.length > 200) {
		return false
	}

	// Only allow alphanumeric, underscore, and hyphen
	return /^[A-Za-z0-9_-]+$/.test(id)
}

/**
 * Extract timestamp from a generated ID (if possible).
 *
 * Only works with IDs generated by `generateId()`.
 *
 * @param id - ID to parse
 * @returns Timestamp or null if not parseable
 */
export function extractTimestamp(id: string): number | null {
	const parts = id.split('-')
	if (parts.length < 1) {
		return null
	}

	try {
		const timestamp = parseInt(parts[0], 36)
		if (Number.isNaN(timestamp)) {
			return null
		}
		return timestamp
	} catch {
		return null
	}
}
